name: aplikasi_targetku
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  cupertino_icons: ^1.0.2

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Models & Immutability
  freezed_annotation: ^2.4.1

  # Functional Programming (Either type)
  fpdart: ^1.1.0

  # Database (SQLite)
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.1.2
  path: ^1.8.3
  # Navigation
  go_router: ^13.2.1

  # Logging
  logger: ^2.2.0
  intl: ^0.20.2
  image_picker: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  flutter_lints: ^2.0.0

  # Code Generators
  build_runner: ^2.4.8
  freezed: ^2.4.7
  riverpod_generator: ^2.4.0
  drift_dev: ^2.15.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true